# Generated by Django 3.0.8 on 2020-09-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piado',
            name='piado_hospedeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='piado.Piado'),
        ),
    ]
